### PR TITLE
N-API Support

### PR DESCRIPTION
**Pull request by jschlight**
This PR replaces the current NAN implementation with an N-API implementation targeted to N-API v3. 

In addition to the methods and properties previously added by @ccollie in PR https://github.com/mcollina/native-hdr-histogram/pull/35, this PR adds the following methods:

```
linearcounts
logcounts
recordedcounts
```

See issue https://github.com/mcollina/native-hdr-histogram/issues/34.

### CODE REVIEW

**Comment by mcollina** [comment]
It seems CI is failing, could you take a look?

**Comment by jschlight** [comment]
Yes. `Environment: nodejs_version=14; Platform: x86` is failing at random for issues that appear related to AppVeyor. This CI on my fork just prior to this PR ran successfully:

https://ci.appveyor.com/project/jschlight/native-hdr-histogram/builds/34484967

**Comment by mcollina** [comment]
I would propose to move to github actions for everything, wdyt? Can you make the change?

**Comment by vweevers** [comment]
Or use `nodejs_version: "14.2.0"` which doesn't have that issue on AppVeyor.

**Comment by mcollina** [comment]
what works for you.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
