### PR TITLE
Add node 10 to travis and appveyor

### PR DESCRIPTION
**Pull request by vweevers**
*If* this works, I'll postpone #19 and we can do a release.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
LGTM

**Comment by vweevers** [comment]
Node 10 on appveyor is failing.

Reverting to defaults worked well for Travis, so I'm gonna try that for AppVeyor as well.

**Comment by vweevers** [comment]
Red diff, green build. That's the best possible outcome

**Pull request merged**
