### PR TITLE
Updated dependencies and added node 9.

### PR DESCRIPTION
**Pull request by mcollina**

### CODE REVIEW

**Comment by GlenTiki** [comment]
This failing build has been annoying me - do you mind if I push to your branch to get this green + merged @mcollina?

**Comment by mcollina** [comment]
Go ahead!!

**Comment by GlenTiki** [comment]
@mcollina I removed the lockfile with one of the latest commits. Seems like we got some ci issues because of it. Plus this is a lib, not an app, so it's uneeded... right?

**Comment by mcollina** [comment]
Node 4 is failing on Travis, and Appveyor is all red :/.

**Comment by mcollina** [comment]
LGTM when everything is green.

**Comment by GlenTiki** [comment]
This has been a really frustrating experience. I'm so close with it!

**Comment by mcollina** [comment]
We can even drop it and mark this module as deprecated. Autocannon now uses a pure-js version of it.
If I had to rewrite this, I would actually see to use a wasm version now.

**Comment by GlenTiki** [comment]
True. With there being a js alternative this should be obsolete. Lets do that, and get this headache over with!

**Comment by vweevers** [comment]
I wish I saw this thread 2 hours ago 😄 before I attempted to fix `native-hdr-histogram` for node 10.

How does the perf of [`hdr-histogram-js`](https://github.com/HdrHistogram/HdrHistogramJS) compare to this?

**Comment by mcollina** [comment]
I did not measure any measurable difference in autocannon.
Il giorno lun 10 set 2018 alle 20:43 Vincent Weevers <
notifications@github.com> ha scritto:

**Comment by vweevers** [comment]
Superseded by #20.

**Pull request closed without merging**
